### ISSUE TITLE
warning: redefining `object_id' may cause serious problems

### ISSUE THREAD

**Issue by alec-c4** [welldan97/protocolist#1]
Hi, i have in logs

/Users/alec/.rvm/gems/ruby-1.9.3-p125@hippflow/gems/activerecord-3.2.6/lib/active_record/attribute_methods/read.rb:74: warning: redefining `object_id' may cause serious problems
/Users/alec/.rvm/gems/ruby-1.9.3-p125@hippflow/gems/activerecord-3.2.6/lib/active_record/attribute_methods/read.rb:86: warning: redefining`object_id' may cause serious problems
/Users/alec/.rvm/gems/ruby-1.9.3-p125@hippflow/gems/activerecord-3.2.6/lib/active_record/attribute_methods/read.rb:74: warning: redefining `object_id' may cause serious problems
/Users/alec/.rvm/gems/ruby-1.9.3-p125@hippflow/gems/activerecord-3.2.6/lib/active_record/attribute_methods/read.rb:86: warning: redefining`object_id' may cause serious problems

but this problem looks like https://github.com/ging/mailboxer/issues/6, could you check plz?

**Comment by welldan97** [comment]
Yes, looks like protocolist issue.

Same thing as in mailboxer — polymorphic association with `object`.
Will need to change `object` name to something else.

**Comment by alec-c4** [comment]
true-true :) so, will you rename? :)

**Comment by welldan97** [comment]
Sure, hope to do it today or tomorrow.

**Comment by alec-c4** [comment]
for example to subject like in timeline_fu :)

**Comment by alec-c4** [comment]
great, thanks dude :)

**Comment by welldan97** [comment]
No problem :)

Ok, just pushed a fix to github repo, so now:
object is renamed to target,
subject is renamed to actor.
